require("prototypes.coin")
require("prototypes.vending")
require("prototypes.scale-machines")
require("prototypes.scale-recipes")
require("prototypes.recipes-sell")
require("prototypes.recipes-buy")
require("prototypes.map-gen-presets")
